# Server settings
server:
  port: 29998
  contextPath: /resource-server

spring:
  http:
    encoding:
      charset: UTF-8
      force: true

security:
  basic:
    enabled: false
  sessions: stateless
  oauth2:
    resource:
      token-info-uri: ${oauth2.token_info_uri}


# LOGGER
logging:
  level:
    root: info
    org.springframework.security: ${log.level}
    com.happylifeplat.security: ${log.level}
  path: "./logs"
  file: "oauth-resource.log"
